spring.application.name=CodeMatrix

spring.datasource.url=jdbc:mysql://localhost:3306/codematrix
spring.datasource.username=root
spring.datasource.password=akkas@2004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=change-this-secret-to-a-long-random-production-secret
app.jwt.expiration-ms=86400000

spring.thymeleaf.check-template-location=false
